on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  test_build_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: test
        working-directory: api
        run: cargo test
      - name: build
        working-directory: api
        run: cargo build
  test_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: install frontend react
        working-directory: frontend
        run: npm ci
      - name: Build frontend react
        working-directory: frontend
        run: npm run build --if-present
      - name: test frontend
        working-directory: frontend
        run: npm test
